use_frameworks!

source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/oneAlon/YAPodSpecs.git"



target 'YABasicUtilites_Example' do
  pod 'YABasicUtilites', :path => '../'

  target 'YABasicUtilites_Tests' do
    inherit! :search_paths

    
  end
end
